# Generated by Django 3.2.18 on 2023-03-28 16:14

from django.db import migrations, models
import frida.models


class Migration(migrations.Migration):

    dependencies = [
        ('frida', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
