# Generated by Django 3.2.18 on 2023-03-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frida', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['author']},
        ),
    ]
