# Generated by Django 3.2.18 on 2023-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frida', '0006_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='untitled', max_length=200, unique=True),
        ),
    ]
