# Generated by Django 3.2.18 on 2023-07-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frida', '0008_auto_20230426_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_on',
        ),
    ]
